### ISSUE TITLE
i could not do the mesh for the airfoil as first step for airfoil optimization 

### ISSUE THREAD

**Issue by eng-jamal2023** [mdolab/MACH-Aero#108]
## Description
i need to run the single point optimization for different airfoil s809 but i get this error 
![image](https://github.com/mdolab/MACH-Aero/assets/139625590/e48cb801-3c68-489b-8d1f-96bbe699de59)

how i could solve this problem

**Comment by eirikurj** [comment]
Closing, duplicate of https://github.com/mdolab/pyhyp/issues/78

**Comment by eng-jamal2023** [comment]
thank you so much .
