### ISSUE TITLE
Possible bug related to the number of cores used

### ISSUE THREAD

**Issue by S5331107** [mdolab/MACH-Aero#121]
### Discussed in https://github.com/mdolab/MACH-Aero/discussions/119

<div type='discussions-op-text'>

<sup>Originally posted by **S5331107** October 26, 2023</sup>
Hello,
I am trying to run a Euler simulation (about 60k elements). However, when I run the code using more than 2 processors then it becomes extremely slow. Using 2 processors is relatively faster than using 1, but using any number of processors more than 2 makes the code extremely slow. Can it be related to the version openmpi that I am using? I'm using openmpi-4.1.5 version
Thank you</div>

**Comment by eirikurj** [comment]
Hi there. We have not experienced any scaling issues with OpenMPI 4.1.5 (docker or native installs) in our runs or tests. If you suspect MPI issues on your system, you can try other versions to verify and confirm, but I doubt that is the case here.
What you are describing sounds more like a resource limitation. Check that you have enough RAM and **physical cores** available on your computer to run the case. Note that CPU hyperthreading will show 2x the number of physical cores, but no speedup is achieved beyond the number of physical cores. So either disable or just `mpirun` with half the reported cores with hyperthreading enabled.
Closing as non-issue.
