### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by haizhou0410** [mdolab/MACH-Aero#129]
Hello, initially when I install openmpi, everything is ok. After I installed anaconda and when I reinstall openmpi, some error happened as follows. Could someone give me some advice? Thank you very much！
============================================================================
== Compiler and preprocessor tests
============================================================================

*** C compiler and preprocessor
checking whether make supports the include directive... yes (GNU style)
checking for gcc... icc
checking whether the C compiler works... no
configure: error: in `/home/haizhou/packages/openmpi-5.0.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by nwu63** [comment]
Closing as off-topic: not related to the MACH-Aero software.
