### ISSUE TITLE
Issues in Plotting of Optimization History

### ISSUE THREAD

**Issue by umarsajjad1992** [mdolab/MACH-Aero#157]
## Description
When running the wing optimization as directed in the tutorial: (https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/machAeroTutorials/opt_aero.html), everything runs smoothly but when we try to visualize the optimization history using the commands listed below, we get an error:

### Steps to reproduce issue

1. python plot_optHist.py --histFile output/opt.hst --outputDir output/

### Current behavior
     Expected here: /home/mdolabuser/packages/OpenVSP/python/openvsp/openvsp/vspviewer
     /home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyoptsparse/pySNOPT/pySNOPT.py:36: 
     UserWarning: snopt module could not be imported from /home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site- 
     packages/pyoptsparse/pySNOPT.
     snopt = try_import_compiled_module_from_path("snopt", _IMPORT_SNOPT_FROM)
     /home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pyoptsparse/pyNLPQLP/pyNLPQLP.py:20: 
     UserWarning: nlpqlp module could not be imported from /home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site- 
     packages/pyoptsparse/pyNLPQLP.
     nlpqlp = try_import_compiled_module_from_path("nlpqlp", THIS_DIR)
     Traceback (most recent call last):
     File "/home/mdolabuser/mount/tut_implementation/wing_opt/10k_mesh_opt/plot_optHist.py", line 23, in <module>
     axes[0].plot("nMajor", "optimality", data=histValues, label="Optimality")
     File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 1688, in plot
     lines = [*self._get_lines(*args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 311, in 
     __call__
     yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
     File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 454, in 
     _plot_args
     linestyle, marker, color = _process_plot_format(
                               ^^^^^^^^^^^^^^^^^^^^^
     File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 185, in 
     _process_plot_format
     raise ValueError(errfmt.format(fmt, "two marker symbols"))
     ValueError: 'optimality' is neither a data key nor a valid format string (two marker symbols)

### Expected behavior
It is expected to show the converge history of the optimization problem.

### Code versions

- Operating System: Ubuntu 20.04
- Running on Docker
- Mach-Aero version: mdolab/public:u22-gcc-ompi-latest

**Comment by eirikurj** [comment]
The issue is that currently, the `plot_optHist.py` script assumes that `snopt` was used as the optimizer. For other optimizers, these entries do not exist. Feel free to submit a PR updating the script to handle different optimizers for plotting.
