### ISSUE TITLE
Add citation page for each repo docs

### ISSUE THREAD

**Issue by nwu63** [mdolab/MACH-Aero#4]
We should add a separate citation page for the docs of each repo, clearly explaining which papers should be cited under which situation. The README should also be updated appropriately.

## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Documentation update

**Comment by jrram** [comment]
Main ADflow paper:
C. A. Mader, G. K. W. Kenway, A. Yildirim, and J. R. R. A. Martins. ADflow—an open-source computational fluid dynamics solver for aerodynamic and multidisciplinary optimization. Journal of Aerospace Information Systems, 2020. doi:10.2514/1.I010796.

When using or mentioning the ANK solver:
A. Yildirim, G. K. W. Kenway, C. A. Mader, and J. R. R. A. Martins. A Jacobian-free approximate Newton–Krylov startup strategy for RANS simulations. Journal of Computational Physics, 397:108741, Nov. 2019. ISSN 0021-9991. doi:10.1016/j.jcp.2019.06.018.

When citing the ADflow adjoint:
G. K. W. Kenway, C. A. Mader, P. He, and J. R. R. A. Martins. Effective adjoint approaches for computational fluid dynamics. Progress in Aerospace Sciences, 110:100542, October 2019. doi:10.1016/j.paerosci.2019.05.002.

@nwu63 : Where should this go, exactly?

**Comment by nwu63** [comment]
The way I did it for pyOptSparse is the following:
- The README has a section called [Citation](https://github.com/mdolab/pyoptsparse#citation), but redirects readers to a page in the docs
- The docs has a page called [Citation](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/citation.html) containing this information

The reason for this is that I think comprehensive information should not be stored in the README but in the documentation site. The citation information in the repo is for people who are going to use the code, so they will be reading the documentation site anyways. The README is more of a gateway/directory of information for people who have just discovered the repository. It doesn't make sense to have substantial information (such as installation instructions or citation instructions) in the README.

**Comment by nwu63** [comment]
Will do. The following repos should also be updated, and the citation information checked since I think there are some newer journal papers that can be cited:
- pySpline and pyGeo
- IDWarp
- pyHyp

**Comment by jrram** [comment]
- pySpline and pyGeo
There is not paper for pySpline, but for pyGeo we still just have a conference paper:

G. K. Kenway, G. J. Kennedy, and J. R. R. A. Martins. A CAD-free approach to high-fidelity aerostruc- tural optimization. In Proceedings of the 13th AIAA/ISSMO Multidisciplinary Analysis Optimization Conference, number AIAA 2010-9231, Fort Worth, TX, 2010. doi:10.2514/6.2010-9231.

- IDWarp, pyHyp:

N. Secco, G. K. W. K. P. He, C. A. Mader, and J. R. R. A. Martins. Efficient mesh generation and deformation for aerodynamic shape optimization. AIAA Journal, 2020. (In press).

**Comment by nwu63** [comment]
Closed via mdolab/idwarp#47 and mdolab/pyhyp#40.
