### ISSUE TITLE
mdolab docker image sudo password

### ISSUE THREAD

**Issue by simranjeetsinghwork** [mdolab/MACH-Aero#79]
I am trying to use mdolab docker image to follow the tutorials, but I can't find the sudo password for "mdolabuser" user.
Starting container as "root" user isn't helping as it apparently breaks all PATH variables, but it might just be a problem with my naive approach. I would appreciate any help.
Regards,
Simranjeet

**Comment by nwu63** [comment]
For normal usage, you shouldn't need a password I think.

**Comment by simranjeetsinghwork** [comment]
Thanks for the reply!
I don't have write privileges when working within the host machine's volume which is bound to container's "/home/mdolabuser/mount/" directory as suggested in tutorial.

![image](https://user-images.githubusercontent.com/105192966/167693602-0bcacd95-deea-49c1-8189-bb5d9f9ba774.png)

So I have resorted to working within some another directory (in container) and manually transferring files between host and container.

**Comment by nwu63** [comment]
This should work just fine:
```
docker run -it --mount type=bind,source=<path-to-MACH-Aero>,target=/home/mdolabuser/MACH-Aero --name app mdolab/public:u20-gcc-ompi-latest
```
I just tested this and I was able to create directories without problems.

Do you need to run `sudo docker` on your computer? You should configure Docker so that it does not need sudo access, see for example instructions [here](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).

**Comment by simranjeetsinghwork** [comment]
I did the same, but it doesnt work for me.
No, I do not need to prefix "docker" with "sudo" so I assume it is already setup as "docker" group (that grants "root" equivalent privileges).

Maybe it has something to do with SELinux rules.
 [https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker](url)
I will try this when I get access to the system.

**Comment by nwu63** [comment]
Yeah this seems like an OS-specific issue with Docker (note that we only test our code on Ubuntu and we don't really provide much support for Docker-based installas), not really something to do with our containers. I'm going to close the issue for now but if you need something from us feel free to comment on the thread again.

**Comment by kfxw** [comment]
Hi,
I'm facing the same problem where I need the password for the 'mdolabusr' user. This is because I need to develop upon adflow so installing other packages with 'apt' is necessary. Would you mind giving me some suggestions to solve this problem? Thanks.

**Comment by eirikurj** [comment]
Our [docs](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/dockerInstructions.html) now include the password.
