### ISSUE TITLE
Problems about ANK & NK

### ISSUE THREAD

**Issue by KW3303** [mdolab/MACH-Aero#81]
## Description

CFD is performed on 4 nodes (112 CPUs). It starts with DADI, then ANK is started when the residual drops to e-2.   But all the aerodynamic performances don't change anymore after several steps, and the CFL value drops quickly till ADflow doesn't work. It can be solved by using "Runge kutta" instead of DADI at the beginning. 

When the residual drops to e-4，it switches to NK, but the NaN error occurs at the first NK step. 

Please explain what causes these problems and how to solve them thoroughly.

**Comment by nwu63** [comment]
Please read the [solver documentation](https://mdolab-adflow.readthedocs-hosted.com/en/latest/solvers.html) thoroughly before asking questions. Also, we will most likely not help you fix your issues regarding convergence, that is something for you to figure out.
