### ISSUE TITLE
Update library import test to give more information

### ISSUE THREAD

**Issue by eirikurj** [mdolab/MACH-Aero#86]
## Issue
We continually receive issues where people have issues compiling MDO Lab codes and the import test of the library fails (e.g.,  https://github.com/mdolab/pyspline/issues/48, https://github.com/mdolab/idwarp/issues/74). The error message does not state what failed, just that it failed. We should try to improve the error message to make it more clear what the issue is.

### Affected repositories
List of repositories that need to be updated (possibly more)

- adflow https://github.com/mdolab/adflow/pull/236
- idwarp https://github.com/mdolab/idwarp/pull/76
- pysurf https://github.com/mdolab/pysurf/pull/17
- pyhyp https://github.com/mdolab/pyhyp/pull/67
- pyspline https://github.com/mdolab/pyspline/pull/50
- cgnsutilities https://github.com/mdolab/cgnsutilities/pull/61

## Possible solution
Instead of suppressing the import failure message, we should print the exception to stdout. I see few options.

1. Update the existing `importTest.py` files. To consolidate a bit, we could add `importTest.py` this to `baseclasses` and have those repositories run that file.
2. Drop the `importTest.py` and write the import test directly in the Makefile

I see the main benefit from option 1 being easier to customize error messages than straight from the Makefile. Also, by using a centralized `importTest.py` it makes the maintenance a bit easier. Once possible drawback is that it will create some inconsistency between packages as some have a local file e.g., `pyspline`, who does not depend on `baseclasses`.

I think the question is, do we see value in `importTest.py` or not, and do we want to keep that centralized. 

Looking for some feedback.

**Comment by eirikurj** [comment]
To give a better idea, I made the changes for idwarp https://github.com/mdolab/idwarp/compare/main...eirikurj:idwarp:updateImportCheck
Error message looks something like
```
python importTest.py libidwarp.so
Testing if module libidwarp can be imported...
Error: /home/eirikurj/git/idwarp/src/f2py/libidwarp.so: undefined symbol: __cgns_MOD_bctypename
Error: library libidwarp.so was not imported correctly
```
The `importTest.py` is general and could be centralized

**Comment by nwu63** [comment]
Yeah this is fine and at least gives the import error. In the future I would prefer to move to something like meson that would give more information during the compilation/linking stages to ensure that all the dependencies are found before compiling the code.

**Comment by eirikurj** [comment]
Ok, lets keep this local then for now. If there are no other comments, I will the PRs for the above repos.

**Comment by nwu63** [comment]
Yeah I think given that we already have the import test script in each repo it's easier to just modify those instead of trying to centralize them. With meson we can specify additional python build dependencies (such as import test or fortdepend) and those would be installed automatically by meson at build time. So we can deal with the centralization once (if) we move to meson.

**Comment by nwu63** [comment]
Closing as completed.
