### ISSUE TITLE
Bug when running MACH-Aero tutorial with SLSQP

### ISSUE THREAD

**Issue by 1064168551** [mdolab/MACH-Aero#96]
## Description
There is a bug when running MACH-Aero tutorial using docker named mdolab/public:u20-gcc-ompi-stable, I would be very grateful if you could help me. 
The bug is
```
'ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 16 -- input 'D' not compatible to 'd'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mdolabuser/mount/opt/aero/aero_opt.py", line 245, in <module>
    sol = opt(optProb, MP.sens, storeHistory=os.path.join(args.output, "opt.hst"))
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 218, in __call__
    slsqp.slsqp(m, meq, la, n, xs, blx, bux, ff, gg, df, dg, acc, maxit,
ValueError: failed in converting 5th argument `x' of slsqp.slsqp to C/Fortran array'
```
### Steps to reproduce issue

1. …
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code versions

- Operating System:
- Python:
- OpenMPI:
- CGNS:
- PETSc:
- Compiler:
- This repository:

**Comment by 1064168551** [comment]
![image](https://github.com/mdolab/MACH-Aero/assets/60784317/20fe9669-a3f5-4b76-b6f6-17f9df301030)

**Comment by 1064168551** [comment]
The figure of the bug was listed, I would be really grateful if you can help me.

**Comment by eirikurj** [comment]
Thanks for the issue. For completeness, please update and populate the remaining issue sections, i.e.,  `Steps to reproduce issue` with minimal steps etc. 

However, I can confirm that the tutorial is broken when running `SLSQP`.  This is due to a recent change in pyOptSparse (see PR https://github.com/mdolab/pyoptsparse/pull/348 for details). We will look into this, but the fundamental problem is that pyGeo DVs are allocated as complex.

In the meantime to circumvent the issue, you can checkout the previous version of pyOptSparse into a separate branch, e.g., `git checkout -b v2.10.0 v2.10.0`.

**Comment by 1064168551** [comment]
Sincerely thanks for your answer and kindness, SLSQP seems OK when I used pyOptSparse 2.10.0.

**Comment by A-CGray** [comment]
For future reference, the solution here is to fix the handling of real and complex values in pyGeo

**Comment by r-quadros** [comment]
@eirikurj : I am running the optimization in docker and facing the same challenge. I am trying to revert back to a previous version of pyOptSparse still the error remains. Here is where I am reverting back in the "repos" folder in the container as seen in the "git status": 
mdolabuser@bf5736a488a8:~/repos/pyoptsparse$ git status
On branch v2.10.0
nothing to commit, working tree clean
mdolabuser@bf5736a488a8:~/repos/pyoptsparse$

and when I try to run the optimization, I get the same error. Is there something I am missing here? I am sorry, I am new to docker and probably I am reverting to a previous branch in a wrong folder.

**Comment by A-CGray** [comment]
Did you pip install pyoptsparse again after checking out the older release?

**Comment by r-quadros** [comment]
@A-CGray : That helped immensely! Opt. running now. Many thanks.

**Comment by r-quadros** [comment]
Any rough time estimate as to when the working docker file will be uploaded? Although I know there is a workaround by reverting to the git version to 2.10.0 when I do a singularity pull (singularity pull docker://mdolab/public:u22-gcc-ompi-stable) I am facing issues in reverting to a different version in the singularity file *.sif. 
Thanks.

**Comment by eng-jamal2023** [comment]
the same problem to me you just need to uninstall  pyOptSparse 2.10.1. SLSQP seems OK when I used pyOptSparse 2.10.0.
